### ISSUE TITLE
Add support for batch consumer (Receiving messages as arraylist)

### ISSUE THREAD

**Issue by jamesdube** [openzipkin/brave#1236]
I have a queue listener where I receive messages as an array list (see method signature) and the tracing listener is trying to cast that to a message hence throwing an exception. Is there a way i can override this or anything, i'd want to add tracing to my application but this is becoming a stumbling block The offending lines of code are highlighted below:

https://github.com/openzipkin/brave/blob/6c44ccd5f545013369059e2223b48caef476c889/instrumentation/spring-rabbit/src/main/java/brave/spring/rabbit/TracingRabbitListenerAdvice.java#L75

Spring Boot Version: ` 2.2.7.RLEASE`

Spring Cloud Version: `Hoxton.RELEASE`

Rabbit queue listener:
```java
    @Override
    @RabbitListener(
            queues = "successful-transactions",
            containerFactory = "simpleRabbitListenerContainerFactory"
    )
    public void dequeue(List<Message> transactions) {
        logger.info("Receiving -> size {}",transactions.size());
    }
```

Stacktrace:
```java
java.lang.ClassCastException: java.util.ArrayList cannot be cast to org.springframework.amqp.core.Message
	at brave.spring.rabbit.TracingRabbitListenerAdvice.invoke(TracingRabbitListenerAdvice.java:76) ~[brave-instrumentation-spring-rabbit-5.9.0.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.$Proxy94.invokeListener(Unknown Source) ~[na:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1486) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1481) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1421) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.executeWithList(SimpleMessageListenerContainer.java:1023) [spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1012) [spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:913) [spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:81) [spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1284) [spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1190) [spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]
```

**Comment by adriancole** [comment]
Hi, james.. thanks for the great issue. Do you feel up to trying a PR to edit that `TracingRabbitListenerAdvice` file to check if the input is a list? Your example listener could end up in an IT in the brave/instrumentation/spring-rabbit to make sure things work. You can look at kafka as that also has batch-receive.

**Comment by jamesdube** [comment]
@adriancole Sure i was going to suggest the same, I'd gladly want to do the PR but i've seen @dengliming has opened #1237 . If any further help is needed please feel free to ping

**Comment by adriancole** [comment]
@jamesdube maybe comment on that then if you have an opinion, thanks. We won't merge today anyway as we want some in different timezone to comment.

**Comment by adriancole** [comment]
workaround going out in 5.12.4
