### ISSUE TITLE
Wrapped Runnable and Callable should delegate toString()

### ISSUE THREAD

**Issue by shmosel** [openzipkin/brave#1379]
When using `CurrentTraceContext.wrap()`, any custom `toString()` implementation from the underlying task is lost.

For example, say we have this class:

```java
class Task implements Runnable {
    @Override
    public void run() {
        System.out.println("run");
    }

    @Override
    public String toString() {
        return "[Description]";
    }
}
```
And we pass an instance to a dead executor:
```java
ExecutorService exec = Executors.newFixedThreadPool(1);
exec.shutdown();
exec.execute(new Task());
```
The output looks like this:

```
Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task [Description] rejected from java.util.concurrent.ThreadPoolExecutor@26be92ad[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	...
```
But when it's passed through `wrap()`, we get the default `brave.propagation.CurrentTraceContext$1CurrentTraceContextRunnable@224edc67` instead of `[Description]`.

Shouldn't the wrapper delegate to the underlying `toString()` implementation?

**Comment by albertorugnone** [comment]
Yyhhmmilklkmmj~~~~
