### ISSUE TITLE
flakey test: brave.jms.ITJms_2_0_TracingMessageConsumer

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/brave#1398]
The below flake happens on occasion. We should fix this, potentially by replacing the test broker with docker as mentioned here https://github.com/openzipkin/brave/pull/1394#pullrequestreview-1807463298

```
[INFO] Running brave.jms.ITJms_2_0_TracingMessageConsumer
12:52:53,484 WARN  [Thread-1 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@75e09567)] client.ActiveMQClientLogger_impl (ActiveMQClientLogger_impl.java:293) - AMQ212037: Connection failure to invm:0 has been detected: AMQ229014: Did not receive data from invm:0 within the -1ms connection TTL. The connection will now be closed. [code=CONNECTION_TIMEDOUT]
Error:  Tests run: 23, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 26.09 s <<< FAILURE! -- in brave.jms.ITJms_2_0_TracingMessageConsumer
Error:  brave.jms.ITJms_2_0_TracingMessageConsumer.receive_customSampler -- Time elapsed: 0.026 s <<< ERROR!
javax.jms.JMSException: AMQ219016: Connection failure detected. Unblocking a blocking call that will never get a response
	at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:560)
	at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:452)
	at org.apache.activemq.artemis.core.protocol.core.impl.ActiveMQSessionContext.addSessionMetadata(ActiveMQSessionContext.java:507)
	at org.apache.activemq.artemis.core.client.impl.ClientSessionImpl.addMetaData(ClientSessionImpl.java:1531)
	at org.apache.activemq.artemis.jms.client.ActiveMQConnection.addSessionMetaData(ActiveMQConnection.java:670)
	at org.apache.activemq.artemis.jms.client.ActiveMQConnection.authorize(ActiveMQConnection.java:660)
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnectionInternal(ActiveMQConnectionFactory.java:925)
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:290)
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:285)
	at brave.jms.ArtemisJmsExtension.newConnection(ArtemisJmsExtension.java:68)
	at brave.jms.JmsExtension.beforeEach(JmsExtension.java:78)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: ActiveMQUnBlockedException[errorType=UNBLOCKED message=AMQ219016: Connection failure detected. Unblocking a blocking call that will never get a response]
	... 13 more

[INFO] Running brave.jms.ITTracingJMSProducer
12:52:59,615 WARN  [main] client.ActiveMQClientLogger_impl (ActiveMQClientLogger_impl.java:413) - AMQ212053: CompletionListener/SendAcknowledgementHandler used with confirmationWindowSize=-1. Enable confirmationWindowSize to receive acks from server!
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.071 s -- in brave.jms.ITTracingJMSProducer
[INFO] Running brave.jms.ITJms_1_1_TracingMessageConsumer
12:53:04,509 WARN  [main] broker.BrokerService (BrokerService.java:2122) - Temporary Store limit is 51200 mb (current store usage is 0 mb). The data directory: /home/runner/work/brave/brave/instrumentation/jms only has 24632 mb of usable space. - resetting to maximum available disk space: 24632 mb
12:53:04,879 WARN  [main] broker.BrokerService (BrokerService.java:2122) - Temporary Store limit is 51200 mb (current store usage is 0 mb). The data directory: /home/runner/work/brave/brave/instrumentation/jms only has 24632 mb of usable space. - resetting to maximum available disk space: 24632 mb
```

**Comment by reta** [comment]
Ah ... this is not Artemis anymore ... I will take it

**Comment by reta** [comment]
Hopefully, fixed by https://github.com/openzipkin/brave/pull/1410
