### ISSUE TITLE
RestEasy does not support the brave container filters

### ISSUE THREAD

**Issue by remmeier** [openzipkin/brave#191]
When using brave with the current Wildfly application server based on RestEasy, I get:

Caused by: java.lang.NullPointerException
    at org.jboss.resteasy.cdi.CdiInjectorFactory.createConstructor(CdiInjectorFactory.java:82)
    at org.jboss.resteasy.spi.ResteasyProviderFactory.injectedInstance(ResteasyProviderFactory.java:2234)
    at org.jboss.resteasy.core.interception.JaxrsInterceptorRegistry$AbstractInterceptorFactory.createInterceptor(JaxrsInterceptorRegistry.java:170)
    at org.jboss.resteasy.core.interception.JaxrsInterceptorRegistry$OnDemandInterceptorFactory.initialize(JaxrsInterceptorRegistry.java:188)
    at org.jboss.resteasy.core.interception.JaxrsInterceptorRegistry$OnDemandInterceptorFactory.checkInitialize(JaxrsInterceptorRegistry.java:203)
    at org.jboss.resteasy.core.interception.JaxrsInterceptorRegistry$OnDemandInterceptorFactory.getInterceptor(JaxrsInterceptorRegistry.java:214)

Having a look at the implementation there is a 

 Constructor<?> constructor = PickConstructor.pickSingletonConstructor(clazz);

Which assumes a default constructor. It does not support things like:

```
@Inject
public BraveContainerResponseFilter(ServerResponseInterceptor responseInterceptor) {
    this.responseInterceptor = responseInterceptor;
}
```

Not sure if the JAX-RS spec allows this. So I updated the implementation to:

  @Inject
    ServerRequestInterceptor interceptor;

```
@Inject
SpanNameProvider spanNameProvider;
```

with a default constructor. Then it seems to work fine.

**Comment by heiko-braun** [comment]
I think the to make it work in Resteasy is to provide customer filter implementation that internally leverage the Brave.Builder() to construct the brave components and instantiate a `BraveContainerResponseFilter` from this, which is then used as a delegate.

**Comment by adriancole** [comment]
is this still an issue? We've added builders and such

**Comment by heiko-braun** [comment]
no, we can close this.

**Comment by adriancole** [comment]
👍
