### ISSUE TITLE
NullPointerException on batch insert with MySQLStatementInterceptor and rewriteBatchedStatements=true

### ISSUE THREAD

**Issue by dmitry-at-genestack** [openzipkin/brave#293]
`MySQLStatementInterceptor` gives NPE on batch insert to MySQL if JDBC connection uses parameter `rewriteBatchedStatements=true` (driver-level rewriting of multiple insert/update prepared statements to a single statement with large number of parameters).

Exception stack trace:
```
java.sql.BatchUpdateException: Unexpected exception encountered during query.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1162)
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1582)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1248)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958)
	at example.StatementInterceptorTest.executeBatchQuery(StatementInterceptorTest.java:74)
	at example.StatementInterceptorTest.testWithRewriteBatchedStatements(StatementInterceptorTest.java:50)
       .....
Caused by: java.sql.SQLException: Unexpected exception encountered during query.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2582)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1543)
	... 35 more
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.mysql.jdbc.StringUtils.findCharset(StringUtils.java:124)
	at com.mysql.jdbc.StringUtils.toString(StringUtils.java:2199)
	at com.mysql.jdbc.PreparedStatement$ParseInfo.getSqlForBatch(PreparedStatement.java:484)
	at com.mysql.jdbc.PreparedStatement.getPreparedSql(PreparedStatement.java:5049)
	at com.github.kristofa.brave.mysql.MySQLStatementInterceptor.preProcess(MySQLStatementInterceptor.java:52)
	at com.mysql.jdbc.MysqlIO.invokeStatementInterceptorsPre(MysqlIO.java:2859)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2580)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
	... 40 more
```

Test & readme for reproducing the bug can be found [here](https://github.com/dmitry-at-genestack/brave-mysql-bug-report).

**Comment by adriancole** [comment]
Thanks for the test case, dmitry. kudos!

for the lazy, can you give a stack trace? that will help too.

**Comment by dmitry-at-genestack** [comment]
I've added stack trace to the first comment, you might have not received it by email, but it is here

**Comment by adriancole** [comment]
thanks. wanna have a go at a fix?

**Comment by dmitry-at-genestack** [comment]
Actually this looks more like a bug in MySQL Connector/J.
[This line](https://github.com/mysql/mysql-connector-j/blob/release/5.1/src/com/mysql/jdbc/PreparedStatement.java#L484) (used in `PreparedStatement.getPreparedSql()` does not check for `this.charEncoding != null`, but [this line](https://github.com/mysql/mysql-connector-j/blob/release/5.1/src/com/mysql/jdbc/PreparedStatement.java#L935) (in `PreparedStatement.asSql()`) has this check.

`MySQLStatementInterceptor` can use `PreparedStatement.asSql()` [here](https://github.com/openzipkin/brave/blob/master/brave-mysql/src/main/java/com/github/kristofa/brave/mysql/MySQLStatementInterceptor.java#L52) (won't throw exception), but this is going to change span annotations. Instead of 
```
INSERT INTO test.test (id, name) VALUES (?, ?)
``` 
span will have annotation 
```
INSERT INTO test.test (id, name) VALUES (0, 'name0'),(1, 'name1'),(2, 'name2'),(3, 'name3'),(4, 'name4'),(5, 'name5'),(6, 'name6'),(7, 'name7'),(8, 'name8'),(9, 'name9')
```
Is this OK?

**Comment by adriancole** [comment]
logging values has a redaction issue (not saying people care, but they might). Is this bug solved in a later version of MySQL connector and/or MariaDB's driver? It seems a bit off to change instrumentation around a bug :P

**Comment by dmitry-at-genestack** [comment]
I've used latest stable MySQL Connector/J (5.1.40), `MySQLStatementInterceptor` just does not work with version 6.0 (development) of MySQL Connector/J.

**Comment by dmitry-at-genestack** [comment]
I have not tried MariaDB Connector/J.

**Comment by adriancole** [comment]
what about specifying the charset.. is there a way you can set that? Maybe
log a bug with MySQL? Solving problems at the right abstraction is usually
a better choice. It would be a weird comment to put into the code :) //
TODO: when this line changes in MySQL connector/j stop logging parameter
values

**Comment by dmitry-at-genestack** [comment]
I'll report a bug in MySQL and put a link here.

**Comment by dmitry-at-genestack** [comment]
Bug report for MySQL Connector/J: http://bugs.mysql.com/bug.php?id=84163

**Comment by adriancole** [comment]
> As a workaround you can use server-side prepared statements (useServerPrepStmts=true) in which this seems not to be a problem.

If there's any follow-up please raise a pull request to change instrumentation/mysql
