### ISSUE TITLE
Exception in function getLocalHostLANAddress() on FreeBSD

### ISSUE THREAD

**Issue by Vanav** [openzipkin/brave#341]
I run Atlassian Confluence 5.10 or 6.0 on JRE 1.8.0_102-b14 on FreeBSD 11, and it can't start because of exception. Can you please check, if function `getLocalHostLANAddress()` works correctly on FreeBSD? I've tried to search for solution, but can't find anything and have a little knowledge to debug myself.

```
Caused by: java.lang.IllegalStateException: Unable to get Inet address
        at com.github.kristofa.brave.Brave$Builder.<init>(Brave.java:59)
        at com.atlassian.confluence.util.zipkin.impl.BraveFactoryBean.createInstance(BraveFactoryBean.java:32)
        at org.springframework.beans.factory.config.AbstractFactoryBean.afterPropertiesSet(AbstractFactoryBean.java:134)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
        ... 107 more
Caused by: java.net.UnknownHostException: Failed to determine LAN address: java.net.SocketException: Cannot assign requested address
        at com.github.kristofa.brave.InetAddressUtilities.getLocalHostLANAddress(InetAddressUtilities.java:80)
        at com.github.kristofa.brave.Brave$Builder.<init>(Brave.java:56)
        ... 111 more
Caused by: java.net.SocketException: Cannot assign requested address
        at java.net.NetworkInterface.getAll(Native Method)
        at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:343)
        at com.github.kristofa.brave.InetAddressUtilities.getLocalHostLANAddress(InetAddressUtilities.java:43)
        ... 112 more
```

**Comment by adriancole** [comment]
This is a bug we can fix. However, you would need to update atlassian
confluence. Can you open an issue there and note back?

**Comment by adriancole** [comment]
fix https://github.com/openzipkin/brave/pull/342
