### ISSUE TITLE
brave-spancollector-scribe:Frame size (1213486160) larger than max length (16384000)!

### ISSUE THREAD

**Issue by catslave** [openzipkin/brave#348]
Hi, I just run demo, like these. 
```
 @Test
	public void contextLoads() {
		collector = new ScribeSpanCollector("localhost", 9411);
		collector.collect(new Span().setTrace_id(1).setName("ScribeServiceTest"));
	}
```

Then throw exception like these.
```
2017-01-24 11:16:52.782  WARN 13268 --- [pool-1-thread-1] c.g.k.brave.scribe.SpanProcessingThread  : Logging spans failed. 1 spans are lost!

org.apache.thrift.transport.TTransportException: Frame size (1213486160) larger than max length (16384000)!
	at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:137) ~[libthrift-0.9.0.jar:0.9.0]
	at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101) ~[libthrift-0.9.0.jar:0.9.0]
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84) ~[libthrift-0.9.0.jar:0.9.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:378) ~[libthrift-0.9.0.jar:0.9.0]
```

I'm not sure what I'm doing wrong.
Thanks for the help!

**Comment by adriancole** [comment]
Scribe is port 9410 not 9411 (in the default zipkin server). If you are
interested in http, I'd recommend looking at the javadoc on
Brave.Builder.reporter() which shows how. Or maybe this example:
https://github.com/openzipkin/brave-webmvc-example

**Comment by catslave** [comment]
@adriancole that done! thank you! In my project will use http, and I also want to know scribe,thank you!
