### ISSUE TITLE
Strange failures on CircleCI pull request builds

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#766]
urefire13866a:377)
22075	at org.ap306168343ache.8tmlogging.lp soguref4j.corire_112298188672826617543tmp
e.layout.PatternLayout.<ini[>(Patte31mERrnLayoRORu] Prt.javocess Exit Code: 0
a:[ERROR] 	at org.apache.maven.plugi12n.surefire.boote9)
	at org.apache.rcllogginieng.log4j.core.layout.Pattert.ForkStartnLaer.yout.<init>(Patterfork(nLaForkStarter.java:671)
yout.java:[ERROR]59)
	at org.apache.lo 	agging.logt org.apa4j.core.layout.PatternLayout$Builder.builche.maven.plugin.surefid(PatternLayout.java:660)
	at org.apache.loggre.booterclient.ForkStarter.ing.log4j.core.config.AbstractConfiguration.setToDefault(AbstractConfiguration.java:583)
	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:47)
	at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContexfork(ForkStarter.java:533)
t.java:88)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(Class[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internalLoaderContextSelector.java:171)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateCon.LitextfecycleStarter.execute(Lifecycle(ClassLoaderConStarter.java:128)
tex[ERROR] 	at otSelector.java:145)
	at org.aparg.apache.che.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:70)
	at org.apache.logging.log4j.core.selectormaven.DefaultMaven.doExec.ClassLoaderContextSelector.getContext(ClassLoaderContute(DefaultMaven.jaextSelector.java:57)
	ava:3t org.ap05) ach[m
e.logging.log4j.co[Ere.impl.Log4jContextFactoRROR] y.m	at org.apgetCoache.maventexn.DefaultMaven.doExect(ute(DefaultMaven.java:192) Lo[m
g[ContextFactory31mERROR [.jm] va:148)
	at org.;31m	at oapachrg.apae.logging.log4j.core.imche.maven.Defpl.Log4jConaultMaventex.execute(DefaultMavetFan.java:ctory.getC105)
ontext(Log4jCon[ERRtextFactoORry.java:45)
	at org.] apache.logging.log4j.LogM	at org.apachanager.getContexe.mavten.(LogManagercli.MavenCli.execute(MavenCli.java:9.java:54)
194[ )
	at org.apache.loggi[1;31ng.mERlog4j.spi.AbROR] 	at stractLoggerAorg.apache.dapter.getCmaven.ontext(AbstractLoggerAdapcli.Mater.jvenClava:12i.doMain(M1)
	at org.apache.loggingavenC.log4j.jul.Abstrali.javactLog:288)
gerAdapter.getContext(Abstract[LoggerAdapteERROR.jm] 	at org.apache.maven.cli.Maveava:34)
	at org.anClipache.main(Maven.lCli.java:1ogging.log4j92)
.s[ERROR] i.AbstractLoggerAdapte31m	at r.getLoggjava.base/jer(AbstractLoggerAddkapter.java:46)
	at org.apache.loggin.interng.loal.reflect.NativeMetg4j.jul.LogManager.getLogger(LogManager.java:89)
	hodAccessorImpl.invoke0(Native Method)
at [ERROR] ava.logging/java.u1;31m	at jtil.loava.base/jdk.igging.LogManager.dnteremandSystemLoggnal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccesser(LogManager.java:571)orImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke
	at java.0(Native Method)
logging/java.util.logging.LogManager$LoggingProviderAccess.demandLoggerFor(LogManager.java:2710)
	at java.logging/sun.util.logging.internal.Loggi[ERRORngProv] 	at java.base/jiderImpl.demandJULLoggerFor(LoggingProviderImpl.java:411)
	at java.loggindk.intg/sun.uternal.reflect.Nail.logging.internalti.LoggingProviderImpl.demandLoggerveMethodAccessorImpl.invoke(NFor(LogginativeMethodAccessorImpl.java:62)
[ERROgProviderImpl.java:436)
R] 	at java.base/jdk.internal.reflect.DelegatingMethodA	at java.base/jdk.internal.logger.DefaultLoccessoggerFinder.getLogger(DefaultLoggerFinder.java:157)
	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggersrImpl..java:389)
	at java.base/jdk.internal.logger.LazyLoginvoke(DelegatingMegers.getLazyLogger(LazyLoggers.java:444)
	at java.base/sun.util.logging.PlthodAccessorImpl.java:43)
atformLogger.getLogger(PlatformLogger.java:297)
	at java.base/sun.util.locale.provider.LocaleServiceProviderPool.config(LocaleServ[ERROR] ceProviderPool.java:125)
	at java.base/sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleServiceProviderPool.java:285)
	at java.base/sun.1;31m	at java.base/java.lang.reflect.Method.invokeutil.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleServiceProviderPool.java:262)
	at java.base/sun.util.locale.provider.CalendarDataUtility.retrieveFirs(Method.java:564)
tDayOfWeek(CalendarDataUtility.java:75)[ [1;31
	at java.base/jmERROR] 	at oava.utilrg.apac.Calendar.setWeekCountData(Calendar.java:3411)
	at java.base/java.util.Calendar.<init>(Calendar.java:1611)
	he.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
at java.base/java.util.[Grgorian;31mERROR] 	at org.apache.maven.wrapper.WrapperExecCalendar.<init>(GregorianCalendar.java:7utor.exe38)
cute(WrapperExecutor.java:122)
	at jav[ERROR] 	at org.apache.maven.wrapper.MavenWrapperMain.maia.base/java.util.Calendar$Builder.build(Calendan(MavenWrapperMain.java:55)
r.java:1493)
	at java.base/sun.util.locale.provider.Cale[darProvid31mERROR] erImpl.getInstance(CalendarProviderImpl.ja
va:87)
	at jav[ a.base[1;31mERROR] -> [Help 1]
/java.util.Calendar.c[ERROR] 
reateCalend[ERROR] To see the full stack trace of the errors, re-run Maven with the -ear(Ca switch.
len[ERROR] Re-run Maven using the -X switdar.java:1ch to enable full debug logging.
696)
	at java.base/jav[ERROR] 
a.util.Cale[dar.getInstance(Calendar.java:1643)
	at org.apache.logging.log4j.core.util.datetime.FixedDateFormat.calcMidnightMillis(FixedDateFormat.java:397)
	at org.apache.logging.log4j.core.util.datetime.FixedDa31mERROReFormat.upm] For more idateMinformadnightMiltiolis(FixedDateFormat.java:38n about the errors and po8)
	ssible solutions,at o please read the follrg.aowpache.ling articles:ogging.log
4j.core.util.dateti[ERROR] [Help 1me].FixedDateFo http:/rmat.millisSinceMidnigh/cwikit(FixedDat.apache.orgeForm/confluence/diat.java:37spl9)
	at org.aay/MAVEN/Mopache.joExecutionExceptionlogging.log4j.core.uti
l.datetime.FixedDateFormat.forma[(FixedDateFormat.j;31mERROR] 
ava:469)
	at org.ap[cmERROR he.logg[m] After correctiing.log4j.core.util.datetime.FixedDateFormang the prot.formatInstant(blems, you can FixedDateFormat.java:439)
	aresume the build with the command
t org.apache.logging.log4j.core.util.datetime.FixedDateFormat.formatInstant(FixedDateFormat.java:434)
	at org.apa[Eche.logging.log4j.core.RROR pattern.DatePatternConverter$FixedFormatter.format(DatePattern[m]    Converter.java:100)
	at[1mmvn org. <goals> -rf :apache.logginbrag.log4j.ve-core.pattern.testsDatePatternC
onverter$CachedTime.<init>(DatePatternConverter.java:155)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter.fromEpochMillis(DatePatternConverter.java:190)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter.<init>(DatePatternConverter.java:184)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter.newInstance(DatePatternConverter.java:208)
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.logging.log4j.core.pattern.PatternParser.createConverter(PatternParser.java:583)
	at org.apache.logging.log4j.core.pattern.PatternParser.finalizeConverter(PatternParser.java:639)
	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:415)
	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:177)
	at org.apache.logging.log4j.core.layout.PatternLayout$SerializerBuilder.build(PatternLayout.java:377)
	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:129)
	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:59)
	at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:660)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.setToDefault(AbstractConfiguration.java:583)
	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:47)
	aExited with code 1

**Comment by adriancole** [comment]
circleci is no more
